// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaT85zIkurgEogtTw5IFdMXVr_hYG2Al8',
    appId: '1:568816791071:web:728d2732e77f169dee2f2a',
    messagingSenderId: '568816791071',
    projectId: 'valor-trading-erp',
    authDomain: 'valor-trading-erp.firebaseapp.com',
    storageBucket: 'valor-trading-erp.appspot.com',
    measurementId: 'G-302NYC0E1W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBiQHUTm6cf6IMbt-9Z-BqRRqVTp62PPA',
    appId: '1:568816791071:android:dbde65e3ed9449e5ee2f2a',
    messagingSenderId: '568816791071',
    projectId: 'valor-trading-erp',
    storageBucket: 'valor-trading-erp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAw4VCkh4co5BcVOqDdsaYCQ3q7fAUKv40',
    appId: '1:568816791071:ios:ac420daee0ce32b9ee2f2a',
    messagingSenderId: '568816791071',
    projectId: 'valor-trading-erp',
    storageBucket: 'valor-trading-erp.appspot.com',
    iosBundleId: 'com.example.valorTrading',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAw4VCkh4co5BcVOqDdsaYCQ3q7fAUKv40',
    appId: '1:568816791071:ios:ac420daee0ce32b9ee2f2a',
    messagingSenderId: '568816791071',
    projectId: 'valor-trading-erp',
    storageBucket: 'valor-trading-erp.appspot.com',
    iosBundleId: 'com.example.valorTrading',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAaT85zIkurgEogtTw5IFdMXVr_hYG2Al8',
    appId: '1:568816791071:web:129360d412ebb043ee2f2a',
    messagingSenderId: '568816791071',
    projectId: 'valor-trading-erp',
    authDomain: 'valor-trading-erp.firebaseapp.com',
    storageBucket: 'valor-trading-erp.appspot.com',
    measurementId: 'G-Z52BNEFR8P',
  );
}
